/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paperme.desktop;

import com.paperme.desktop.gui.login.Login;

public class App {
    public static void main(String[] args) {
      new Login().setVisible(true);
    }
}
