/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paperme.desktop;

import com.paperme.desktop.gui.GUI;

public class App {
    public static void main(String[] args) {
      GUI gui = new GUI();
      gui.run();
    }
}
